### ISSUE TITLE
USER STORY: Navigation

### ISSUE THREAD

**Issue by HMuraja** [HMuraja/p5-book-review#1]
As a **user** I can **view a navbar from every page** so that **I can navigate easily between pages**.

### Acceptance Criteria:
- [x] **Acceptance Criteria 1:** The navbar is visible on each page and all icons are clear and reable.
- [x] **Acceptance Criteria 2:** The navbar collapses on mobile view.
- [x] **Acceptance Criteria 3:** Home, log in and sign up links are the only visible  links for users that are **not** logged in.
- [x] **Acceptance Criteria 4:** Home, log out, add review, my profile and liked links are visible  only for the logged in users.

### Tasks

- [x] Create a navbar to the top of the page.
- [x] Add links to log in and sign up. 
- [x] Add link to log out.
- [x] Add link to home.
- [x] Add link to feed, profile and liked.
- [x] Add link to add review.
- [x] Add logos to the links.
