### ISSUE TITLE
USER STORY: Follow Model

### ISSUE THREAD

**Issue by HMuraja** [HMuraja/p5-book-review#11]
As a **user** I can **follow users that I like** so that **I modify my personal feed to include reviews from users I like**

### Acceptance Criteria:
- [x] **Acceptance Criteria 1:** Followed field and following fields of the instance should be unique pairs in order to avoid duplicate follows from one person.
- [x]  **Acceptance Criteria 2:** Users can easily create follow instance and delete it.
- [x] **Acceptance Criteria 3:** User id is automatically added to the following field in creation.

### Tasks
- [X] Create Follower Model
- [x] Add related_name attribute to the owner and followed attribute of the Follower model to separate the user id references.
- [x] Make a follower serializer add a create method with validated_data as an argument and use try block to avoid duplicate.
- [x] On the interface user must choose the post they want to generate instance, the review id is saved to the instance as review attribute.
- [X] Create a view to list and create all Like instances.
- [X] Create a view to view and delete individual instances of Like model.
