### ISSUE TITLE
USER STORY: Profile Summary - Backend

### ISSUE THREAD

**Issue by HMuraja** [HMuraja/p5-book-review#12]
As a **user/viewer** I can **view anyone's profile details** so that **I can see a summary of their interactions and activity**.

### Acceptance Criteria:
- [x] **Acceptance Criteria 1:** List all reviews for the specified user profile. 
- [x] **Acceptance Criteria 2:** List all the followed ids for the specified user profile.
- [x] **Acceptance Criteria 3:** List all the follower ids for the specified user profile.

### Tasks

- [X] Add view to list all profiles and ensure no permission classes are added. 
- [X] Add a detail view to see individual profiles.
- [x] Define Review models owner attribute to be foreign key of the User.id.
- [x] Define Follow models followed attribute to be foreign key of the User.id.
- [x] Define Follow models owner attribute to be foreign key of the User.id.
- [x] Add follower, followed and reviews count for each profile as an additional field.
- [x] Add filter to the reviews list-view to filter all reviews for the specific profile.
- [x] Add a filter to profiles list-view to filter all followed profiles and another to view all follower profiles.
- [x] Add additional fields to the profile serializer to display associated follows, reviews and followed counts.
