### ISSUE TITLE
USER STORY: API and Front End Communication

### ISSUE THREAD

**Issue by HMuraja** [HMuraja/p5-book-review#13]
As a **user** I can **easily access data saved on the application** so that **I can interact with others and the application seamlessly.**

### Acceptance Criteria:
- [x] **Acceptance Criteria 1:** Build an API that generates JSON data for the front end to consume.
- [x]  **Acceptance Criteria 2:** Front end is able to send data to the API to consume. 
- [x] **Acceptance Criteria 3:** Application features behave smoothly and easy to understand manner.

### Tasks

- [X] Add JWT(JSON Web Tokens) to the deployed API, to ease the user authorisation.
- [X] Add Django allauth to the API so that users can register profiles. 
- [X] Add placeholder image profile in Cloudinary
- [X]  Create a view to list all profile instances.
- [X] Create a view to view and edit individual instances of Profile model.
- [x] Add serializer to serlialize all the model data.
- [X] Add extra fields to the serializer so that profiles followers, followed and post count can be viewed.
- [X] Add a filter and sorting  functionalities to the views.
- [x] Apply appropriate setting for token use to the API project setting folder and env.py
- [x] Create a serializer to return the profile id and profile image data for the logged in users.
