### ISSUE TITLE
USER STORY: Frontend Design 

### ISSUE THREAD

**Issue by HMuraja** [HMuraja/p5-book-review#14]
As a **designer** I can **create an aesthetic and simple interface for the application ** so that **users will keep coming back to using the application**.

### Acceptance Criteria:
- [x] **Acceptance Criteria 1:** Front end has a pleasing color scheme that does not making harder to perform functions or navigate on the site.
- [x] **Acceptance Criteria 2:** Front end layout is intuitive and all the functions are easy to find.
- [x] **Acceptance Criteria 3:** Logo and color-scheme are consistent throughout features creating a pleasant user interface.

### Tasks

- [X] Install React-Bootstrap to facilitate the design.
- [X] Add customized design through css.
