### ISSUE TITLE
USER STORY: Read Reviews

### ISSUE THREAD

**Issue by HMuraja** [HMuraja/p5-book-review#15]
As a **user** I can **easily access the reviews made by others** so that **I can read content made by other users**.

### Acceptance Criteria:
- [x] **Acceptance Criteria 1:** Any user logged in or not can view list of reviews on the home page.
- [x]  **Acceptance Criteria 2:** Any user can view review details by clicking the review. 
- [x] **Acceptance Criteria 3:** Review details all the information reader might be interested of.
- [x] **Acceptance Criteria 4:** Users easily find the reviews they are interested of. 
- [x] **Acceptance Criteria 5:** Listed reviews display an easy to disgest summary of the review.
-
### Tasks

- [x] Implement a reviews page.
- [x] implement review details page.
- [x] Implement a search bar on the list view. 
- [x] Style list view so that it includes at least the reviewed books title, rating and cover image.
- [x] Implement a sort function on the list view.
- [x] Style details view so that image, title, reviewer, author, created on date, reviewed on date and the review content is clearly displayed.
