### ISSUE TITLE
USER STORY: Like reviews

### ISSUE THREAD

**Issue by HMuraja** [HMuraja/p5-book-review#17]
As a **logged in user** I can **like a review ** so that **I can encourage reviews I deem good or/and share my opinion on the posted review**.

### Acceptance Criteria:
- [x] **Acceptance Criteria 1:** A easily visible like button is present in all reviews.
- [x]  **Acceptance Criteria 2:** In the review details user can like/unlike a post by just clicking the hart icon present.
- [x] **Acceptance Criteria 3:** A number of total likes is visible on the review.
- [x] **Acceptance Criteria :** Indicate to the user if they have already liked a post.

### Tasks

- [x] Add like button to reviews view and review details. 
- [x] Create a state that updates the like data.
- [x] Implement the change of heart icon depending on if user has liked it. 
- [x] Prevent users that aren't logged in from liking reviews. 
- [x] Add liked reviews to the liked feed.
