### ISSUE TITLE
USER STORY: View Comments

### ISSUE THREAD

**Issue by HMuraja** [HMuraja/p5-book-review#19]
As a **a user** I can **read comments** so that **I can see what is the reception for the review*.

### Acceptance Criteria:
- [x] **Acceptance Criteria 1:** Any user logged in or not can view comments.

### Tasks
- [x] List comments made on the review details view. 
- [x] Display number of comments made on the review details page.
