### ISSUE TITLE
USER STORY: Routing

### ISSUE THREAD

**Issue by HMuraja** [HMuraja/p5-book-review#2]
As a **user** I can **navigate through pages quickly** so that **I can view content seamlessly without page refresh**.

### Acceptance Criteria:
- [x] **Acceptance Criteria 1:** When any link on the pages is clicked only the relevant components will refresh.

### Tasks

- [x] Nest components in relevant order.
- [x] Route refresh so that only the relevant components refresh. 
- [x] Install the react-router library.
- [x] Wrap App.js inside the Router inside the index.js
- [x] Add switch inside the App.js container and place routes inside it
