### ISSUE TITLE
USER STORY: Edit profile

### ISSUE THREAD

**Issue by HMuraja** [HMuraja/p5-book-review#20]
As a **user** I can **view, edit or delete my profile** so that **I have full control over how I am displayed on this website**

### Acceptance Criteria:
- [x] **Acceptance Criteria 1:** My profile is easy for the user to access. 
- [x]  **Acceptance Criteria 2:** Editing and deleting the profile is easy and straight forward
- [x] **Acceptance Criteria 3:** User can personalize the profile to reflect them.
- [x]  **Acceptance Criteria 3:** Profile displays clear summary of the user details. 

### Tasks

- [x] Create profile page.
- [x] Add a easy to spot link to the profile page,.
- [x] Display user details on the page. 
- [x] Add a edit link to access edit profile page. 
- [x] Create user profile page.
