### ISSUE TITLE
USER STORY: User Profile View

### ISSUE THREAD

**Issue by HMuraja** [HMuraja/p5-book-review#21]
As a **user** I can **view other user profiles** so that **I can find and follow like minded users**.

### Acceptance Criteria:
- [x] **Acceptance Criteria 1:** User profiles are accessible for all users. 
- [x]  **Acceptance Criteria 2:** User profiles summarize the profile offer meaningful data of the selected user. 

### Tasks

- [x] List user details on the profile page. 
- [x] List most recent reviews on the profiles.
- [x] Display follower numbers on the profile. 
- [x] Add a link to each profile image for users to click on.
