### ISSUE TITLE
USER STORY: Authentication - Frontend

### ISSUE THREAD

**Issue by HMuraja** [HMuraja/p5-book-review#3]
As a **user** I can **easily login and logout** so that **I can access the content and be recognized as a logged in user by the application**.

### Acceptance Criteria:
- [x] **Acceptance Criteria 1:** Users are required to log in before accessing any of the CRUD functionalities, apart from signing up.
- [x] **Acceptance Criteria 2:** Logged in user can access all the features of the application once logged in.
- [x] **Acceptance Criteria 3:** User who hasn't logged in can't access urls that they aren't authorized to and are redirected to the home page.

### Tasks

- [x] Make links and functionalities accessible relate the logged in status.
- [x] Block unauthorized users from relevant urls.
- [x] Display logged users id on the nav menu indicate who is logged in.
