### ISSUE TITLE
USER STORY: Authentication - Backend

### ISSUE THREAD

**Issue by HMuraja** [HMuraja/p5-book-review#4]
As a **user** I can **easily login and logout** so that **I can access the content and be recognized as a logged in user by the application**.

### Acceptance Criteria:
- [x] **Acceptance Criteria 1:** An instance of user and profile model class are created when user signs up.
- [x] **Acceptance Criteria 1:** Users id is automatically added to any of the instances they create.
- [x] **Acceptance Criteria 1:** Users can't create instances without being logged in.

### Tasks

- [x] On  creation of a new user instance a new profile model instance is created.
- [x] Add user id as the foreign key owner fields on review, like, profile and comment when they create an instance.
- [x] Add user id as foreign key into the following_id field, when they create an instance.
- [x] Use Rest Frameworks permissions class when crating views for creating and editing models.
- [x] Add user id to the instances user creates.
- [x] Add JWT(JSON Web Tokens) to the application to imporve performance and increase security and enable the automatica logghing out of the user.
