### ISSUE TITLE
USER STORY: Profile Model

### ISSUE THREAD

**Issue by HMuraja** [HMuraja/p5-book-review#5]
As a **user** I can **view, edit and delete my profile** so that **I can personalize my account and view my data**

### Acceptance Criteria:
- [x] **Acceptance Criteria 1:** A profile is automatically created and saved after user is created.
- [x]  **Acceptance Criteria 2:** A placeholder image is added initially when profile is created.
- [x] **Acceptance Criteria 3:** Profiles can be sorted based onn filters and order parameters. 
- [x] **Acceptance Criteria 4:** Profile has a description field that the user can add.
- [x] **Acceptance Criteria 5:** User can edit username, password and profile image to their profile.

### Tasks

- [X] Create Profile Model
- [X] Connect django project to cloudinary storage
- [X] Add placeholder image profile in Cloudinary
- [X]  Create a view to list all profile instances.
- [X] Create a view to view and edit individual instances of Profile model.
- [x] Add serializer to serlialize all the model data.
- [X] Add extra fields to the serializer so that profiles followers, followed and post count can be viewed.
- [X] Add a filter and sorting  functionalities to the views.
