### ISSUE TITLE
USER STORY: Review Model

### ISSUE THREAD

**Issue by HMuraja** [HMuraja/p5-book-review#6]
As a **user** I can **create, edit and delete review** so that **I can share a review on books l have read**

### Acceptance Criteria:
- [x] **Acceptance Criteria 1:** User can create and delete a review.
- [x]  **Acceptance Criteria 2:** User can edit the title, caption, content and image.

### Tasks

- [X] Create Review Model
- [X] Add placeholder image profile in Cloudinary
- [X] Create a view to list all review instances.
- [X] Create a view to view and edit individual instances of Review model.
- [x] Add serializer to serlialize all the model data.
- [X] Add extra fields to the serializer so that review instances fetch related data on comment count, like ids, and like cunt.
