### ISSUE TITLE
USER STORY: Comment Model

### ISSUE THREAD

**Issue by HMuraja** [HMuraja/p5-book-review#7]
As a **user** I can **easily create a comment and edit/delete it if i want to ** so that **I discuss of any reviews I am interested of**

### Acceptance Criteria:
- [x] **Acceptance Criteria 1:** User can add a comment to a review they like.
- [x]  **Acceptance Criteria 2:** Review id is added automatically to the comment instance.
- [x] **Acceptance Criteria 3:** User can edit or delete an comment instance they made.

### Tasks

- [X] Create Comment Model
- [x] On the interface user must choose the post they want to generate instance, the review id is saved to the instance as review attribute.
- [X] Create a view to list and create all Comment instances.
- [X] Create a view to view and edit individual instances of Comment model.
- [x] Add serializer to serlialize all the model data.
