### ISSUE TITLE
USER STORY: View Comment Instances

### ISSUE THREAD

**Issue by HMuraja** [HMuraja/p5-book-review#8]
As a **viewer** I can **easily see comments other have made to the review** so that **I can see what other people though about the review**

### Acceptance Criteria:
- [x] **Acceptance Criteria 1:** List all comment instances.
- [x]  **Acceptance Criteria 2:** Filter comment instances based on the review.

### Tasks

- [x] No tasks yet
