### ISSUE TITLE
USER STORY: Like Model

### ISSUE THREAD

**Issue by HMuraja** [HMuraja/p5-book-review#9]
As a **user** I can **boost the reviews I think are good** so that **I can have an impact on the quality of the reviews posted**

### Acceptance Criteria:
- [x] **Acceptance Criteria 1:** Logged in user can create and delete an like instance
- [x]  **Acceptance Criteria 2:** Creating an instance automatically adds the liked review id to the like field.

### Tasks

- [X] Create Like Model
- [x] On the interface user must choose the post they want to generate instance, the review id is saved to the instance as review attribute.
- [X] Create a view to list and create all Like instances.
- [X] Create a view to view and delete individual instances of Like model.
- [x] Add serializer to serlialize all the model data.
